drop schema public cascade;
create schema public;
update pg_database set encoding = pg_char_to_encoding('UTF8') where datname = 'postgres';

CREATE TABLE contractor (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	public_id varchar(250) NOT NULL,
	privatekey varchar(250) NOT NULL,
	usertype varchar(250) NOT NULL,
	status int NOT NULL DEFAULT 1,
	name  varchar(15) NOT NULL,
	email varchar(250) NOT NULL,
	password text NOT NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,    
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	
	UNIQUE(public_id)
);


CREATE TABLE contractor_profile (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	contractor_id int NOT NULL references contractor(id),
	profile_photo text NULL,
	title varchar(250) NULL,
	bio text NULL,
	domain varchar(50) NULL,
	phone varchar(250) NULL,
	address varchar(250) NOT NULL,
	city varchar(250) NULL,
	state varchar(250) NULL,
	zipcode varchar(10) NULL,
	background text NULL,
	profile_photo text NULL,
	url varchar(250) NULL,
	twitterHandle  varchar(250) NULL,
	facebookHandle varchar(250) NULL,
	instagramHandle  varchar(250) NULL,
	linkedinHandle   varchar(250) NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,    
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE messagestype(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description varchar(250) NOT NULL
);

CREATE TABLE templates(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	templatetypeid int references messagestype(id),
	fromname varchar(250) NOT NULL,
	fromemail varchar(250) NOT NULL,
	subject varchar(250) NOT NULL,
	template text NOT NULL,
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE practice_areas (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(250) NOT NULL,
	status int NOT NULL DEFAULT 0
);

CREATE TABLE contractor_practice_areas (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	contractor_id int NOT NULL references contractor(id),
	practice_area_id int NOT NULL references practice_areas(id)
);


CREATE TABLE owner (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	public_id varchar(250) NOT NULL,
	privatekey varchar(250) NOT NULL,
	status int NOT NULL DEFAULT 1,
	photo varchar(250) NULL,
	firstname  varchar(250) NOT NULL,
	 lastname varchar(250) NOT NULL,
	email varchar(250) NOT NULL,
	password text NOT NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,    
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	usertype varchar(250) NOT NULL DEFAULT 'owner',
	UNIQUE(public_id)
);


CREATE TABLE project (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	owner_id int NOT NULL references owner(id),
	title varchar(250) NOT NULL,
	keywords varchar(25) NOT NULL,
	description text NOT NULL,
    domain varchar(250) NOT NULL,
    address varchar(250) NOT NULL,
	city varchar(250) NULL,
	state varchar(250) NULL,
	zipcode varchar(10) NULL,
	status varchar(15) NOT NULL DEFAULT 'owner',
	project_photo1 text NULL,
	project_photo2 text NULL,
	project_photo3 text NULL,
	project_photo4 text NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,    
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE project_photos (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_id int NOT NULL references project(id),
	photo varchar(250) NOT NULL

);

CREATE TABLE quote (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_id int NOT NULL references project(id),
	employer_id int NOT NULL,
	price int NOT NULL,
	date varchar(250) NOT NULL,
	status varchar(15) NOT NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,    
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);


CREATE TABLE materials (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_id int NOT NULL references project(id),
	material varchar(250) NOT NULL,
	cost int NOT NULL,
	quanity int NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,    
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE labor(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employer_id int NOT NULL,
	price int NOT NULL,
	payout_type varchar(12) NOT NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,    
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP	
);

CREATE TABLE review (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	project_id int NULL references project(id),
	review text NULL,
	communication int,
	pricing int NULL,
	quality int NULL,
	duration int NULL,
	response int NULL,
	six_months int NULL,
	two_years int NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,    
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE chat (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_1 int NOT NULL,
	user_2 int NOT NULL
);

CREATE TABLE message (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	chat_id int NOT NULL references chat(id),
	sent_from int NOT NULL,
	sent_to int NOT NULL,
	message text NOT NULL,
	message_type varchar(20) NOT NULL,
	attachment text NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,    
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



